//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnevnik
    {
        public int id_dnevnik { get; set; }
        public string radnja { get; set; }
        public System.DateTime datum { get; set; }
        public double kolicina { get; set; }
        public Nullable<int> stavka_id { get; set; }
        public Nullable<int> korisnik_id { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual stavka stavka { get; set; }
    }
}
