//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        public korisnik()
        {
            this.dnevnik = new HashSet<dnevnik>();
            this.prostorija = new HashSet<prostorija>();
            this.spremnik = new HashSet<spremnik>();
            this.stavka = new HashSet<stavka>();
        }
    
        public int id_korisnik { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
    
        public virtual ICollection<dnevnik> dnevnik { get; set; }
        public virtual ICollection<prostorija> prostorija { get; set; }
        public virtual ICollection<spremnik> spremnik { get; set; }
        public virtual ICollection<stavka> stavka { get; set; }
    }
}
