//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class prostorija
    {
        public prostorija()
        {
            this.spremnik = new HashSet<spremnik>();
        }
    
        public int id_prostorija { get; set; }
        public string naziv_prostorije { get; set; }
        public System.DateTime datum_kreiranja { get; set; }
        public string opis { get; set; }
        public string posebne_napomene { get; set; }
        public Nullable<int> korisnik_id { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual ICollection<spremnik> spremnik { get; set; }
    }
}
