//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavka
    {
        public stavka()
        {
            this.oznaka = new HashSet<oznaka>();
            this.dnevnik = new HashSet<dnevnik>();
        }
    
        public int id_stavka { get; set; }
        public string naziv { get; set; }
        public System.DateTime datum_kreiranja { get; set; }
        public Nullable<System.DateTime> datum_roka { get; set; }
        public int zauzeće { get; set; }
        public Nullable<int> spremnik_id { get; set; }
        public Nullable<int> korisnik_id { get; set; }
    
        public virtual spremnik spremnik { get; set; }
        public virtual ICollection<oznaka> oznaka { get; set; }
        public virtual ICollection<dnevnik> dnevnik { get; set; }
        public virtual korisnik korisnik { get; set; }
    }
}
