//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tip_spremnika
    {
        public tip_spremnika()
        {
            this.spremnik = new HashSet<spremnik>();
            this.oznaka = new HashSet<oznaka>();
        }
    
        public int id_tip { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<spremnik> spremnik { get; set; }
        public virtual ICollection<oznaka> oznaka { get; set; }

        public override string ToString()
        {
            return naziv;
        }
    }
}
